### ISSUE TITLE
need README instructions for each of the providers

### ISSUE THREAD

**Issue by csells** [davidmigloz/flutter_ai_community#2]
otherwise, how will people know how to configure them?

**Comment by davidmigloz** [comment]
Do you think we need more than the existing ones?
https://github.com/davidmigloz/flutter_ai_community/tree/main/packages/flutter_ai_providers

For all of them it's basically, go to the provider console, grab your key and instantiate the provider with the model you want to use.

**Comment by csells** [comment]
I had to idea to look at those. I was looking at the top level README. But I just the one for the package will be the one on pub, so the existing docs should be fine.
